apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-etcdencryption-gitops-hohset
  namespace: default
placementRef:
  name: placement-policy-etcdencryption-gitops-hohset
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
subjects:
  - name: policy-etcdencryption-gitops-hohset
    kind: Policy
    apiGroup: policy.open-cluster-management.io
